<section id="left-navigation">
<!--Left navigation user details start-->
<div class="user-image">
    <img src="../images/demo/avatar-80.png" alt="">
    <div class="user-online-status"><span class="user-status is-online  "></span> </div>
</div>
<ul class="social-icon">
    <li><a href="javascript:void(0)"><i class="fa fa-facebook"></i></a></li>
    <li><a href="javascript:void(0)"><i class="fa fa-twitter"></i></a></li>
    <li><a href="javascript:void(0)"><i class="fa fa-github"></i></a></li>
    <li><a href="javascript:void(0)"><i class="fa fa-bitbucket"></i></a></li>
</ul>
<!--Left navigation user details end-->

<!--Phone Navigation Menu icon start-->
<div class="phone-nav-box visible-xs">
    <a class="phone-logo" href="index.html" title="">
        <h1>Fickle</h1>
    </a>
    <a class="phone-nav-control" href="javascript:void(0)">
        <span class="fa fa-bars"></span>
    </a>
    <div class="clearfix"></div>
</div>
<!--Phone Navigation Menu icon start-->

<!--Left navigation start-->
<ul class="mainNav" style="">
<li class="active">
    <a class="active" href="index.html">
        <i class="fa fa-dashboard"></i> <span>首页</span>
    </a>
</li>
<li>
    <a href="productManage.html">
        <i class="fa fa-envelope-o"></i> <span>产品管理</span><span class="badge badge-red">3</span>
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-envelope-o"></i> <span>订单管理</span><span class="badge badge-red">3</span>
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-envelope-o"></i> <span>用户管理</span><span class="badge badge-red">3</span>
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-envelope-o"></i> <span>商户管理</span><span class="badge badge-red">3</span>
    </a>
</li>
<li>
    <a href="baseCollocate.html">
        <i class="fa fa-envelope-o"></i> <span>基础配置</span><span class="badge badge-red">3</span>
    </a>
</li>
<li>
    <a href="timeline.html">
        <i class="fa fa-clock-o"></i> <span>TimeLine</span>
    </a>
</li>
</ul>
<!--Left navigation end-->
</section>